### ISSUE TITLE
Stateful parsers

### ISSUE THREAD

**Issue by Artentus** [benjamin-hodgson/Pidgin#108]
Hello,

I just extended the library to support a user defined state on the parser in my fork.  
Tests and examples have all been updated and I've added a couple new tests relating to the user state as well.

Now I want to ask if you're interested in a PR. Usually I'd just send one but due to the additional generic parameter this will break code-compatibility. Not hard to update but possibly tedious in large existing codebases. And I also don't know if this fits your original vision for the library.

**Comment by benjamin-hodgson** [comment]
Thanks for your interest!

Early on I chose not to support user state, primarily because a three-parameter type is a bit too much complexity (and typing!) for a C# library. (I would be much less hesitant to add type params in a language with less verbose generics and better type inference.) I basically chose supporting arbitrary input streams over user state.

There are certain things which are made much easier by state variables, such as indentation-sensitive parsing, but the majority of parsing tasks don't require it. I think it's also quite easy to misuse and write parsers which are too complex.

All that is to say: "Pidgin-with-user-state" is a different library than Pidgin. I wholeheartedly encourage you to write your own library and contribute to a vibrant ecosystem with many options. Let a thousand flowers bloom!

**Comment by Artentus** [comment]
I suspected this would be your answer, and I completely understand, that's why I asked.

I chose Pidgin for my project because I think it's the best parser library for C# out there, but I was missing this one thing.  
Adding a couple of type parameters and then publishing it as "my own" library feels pretty cheap to me since it's still basically all your work, although I realize the license does allow it.
