### ISSUE TITLE
Make generics more clear

### ISSUE THREAD

**Issue by Shadowblitz16** [benjamin-hodgson/Pidgin#109]
Please Rename T to TResult, and U to whatever it is

Its really hard to understand what they are when they are just named T and U.

**Comment by benjamin-hodgson** [comment]
The names are short and non-committal by design. `T` is used in a variety of different ways - not always as a result. Take [`Then`](https://www.benjamin.pizza/Pidgin/v2.5.0/api/Pidgin.Parser-2.html#Pidgin_Parser_2_Then__2_Pidgin_Parser__0___0__Func__1___0___1__) for example:

```csharp
Parser<TToken, R> Then<U, R>(Parser<TToken, U> parser, Func<T, U, R> result)
```

`R` has the greatest claim to be considered the "result type" here (hence why I called it `R`). `T` and `U` are both used as _inputs_ to `Then` - or perhaps you could consider them intermediate results. Either way, renaming `T` to `TResult` would be actively misleading in this context, as well as being wordy.

`TToken`, on the other hand, is used uniformly as the type of input tokens throughout the library.

**Comment by Shadowblitz16** [comment]
what about `TOut` and `TIn`?

**Comment by benjamin-hodgson** [comment]
I personally don't think `TOut` and `TIn` are improvements. I'm open to suggestions of specific places the names could be clearer but I am not planning a full-scale change to my naming strategy otherwise.
