### ISSUE TITLE
`Separated` seems to be failing, despite finding matches.

### ISSUE THREAD

**Issue by atrauzzi** [benjamin-hodgson/Pidgin#128]
I have the following parser which is meant to consume sequences I'm calling _identifiers_ which look `"something like this"`.

In some places, I'd like to accept a comma-separated list of identifiers, so I have the following:

```csharp

public static Parser<char, char> Comma => SkipWhitespaces.Then(Char(',')).Before(SkipWhitespaces);

public static Parser<char, Identifier> IdentifierWithoutGroup => Char('"')
    .Then(SkipWhitespaces)
    .Then(IdentifierName.ManyString())
    .Map((name) => new Identifier(name))
    .Before(SkipWhitespaces)
    .Before(Char('"'));

public static Parser<char, IEnumerable<Identifier>> Parameters => SkipWhitespaces
    .Then(IdentifierWithoutGroup
        // note: This trace produces output as I expect!
        .TraceResult()
        .Separated(Comma))
    // note: This trace never produces output!
    .TraceResult();
```

As I've noted in the comments above, I'm experiencing this weird issue where `Parameters` is failing, but by all accounts, I can't figure out why?

_Apologies for what I'm gonna guess is a pretty minor mistake.  I'm still learning Pidgin :slightly_smiling_face:_

**Comment by benjamin-hodgson** [comment]
(I’m on my phone so can’t test your code, but) the `SkipWhitespaces` at the start of `Comma` looks suspicious to me. If the `Comma` parser consumes any input (that is, any whitespace) then the `Separated` parser will commit to it. So the input `foo ` will fail because no `,` was found after the space at column 4.

I generally like to call `SkipWhitespaces` only after consuming each token. See my website for a thorough example: https://www.benjamin.pizza/posts/2019-12-08-parsing-prolog-with-pidgin.html#handling-tokens-and-whitespace

**Comment by atrauzzi** [comment]
Thanks!  I'll dig into it further!
