### ISSUE TITLE
Error with sequencing parsers on .NET Core 2.1

### ISSUE THREAD

**Issue by valxv** [benjamin-hodgson/Pidgin#13]
This test
```csharp
[Theory]
[InlineData("<>", 1)]
[InlineData("<", 2)]
[InlineData(">", 3)]
[InlineData("=", 4)]
public void TryParse(string source, int expected)
{
    Parser<char, int> parser =
        Parser.Char('<').Then(_ => Parser.Char('>')).ThenReturn(1)
        .Or(Parser.Char('<').ThenReturn(2))
        .Or(Parser.Char('>').ThenReturn(3))
        .Or(Parser.Char('=').ThenReturn(4));
     
    Assert.Equal(expected, parser.ParseOrThrow(source));
}
```
fails with the following error

> Failed   PidginTests.PidginTests.TryParse(source: "<", expected: 2)
Error Message:
 Pidgin.ParseException : Parse error.
    unexpected EOF
    expected "<"
    at line 1, col 2
Stack Trace:
   at Pidgin.ParserExtensions.GetValueOrThrow[TToken,T](Result`2 result)
   at Pidgin.ParserExtensions.ParseOrThrow[T](Parser`2 parser, String input, Func`3 calculatePos)
   at PidginTests.PidginTests.TryParse(String source, Int32 expected)

Other tests in theory passed.
Verified on Windows 10 and MacOS.

**Comment by benjamin-hodgson** [comment]
Thanks for getting in touch! Your parser is of the form:

```csharp
Char('<').Then(Char('>))
    .Or(...);
```

(I recommend putting `using static Pidgin.Parser; using static Pidgin.Parser<char>;` at the top of your file so you don't have to repeat the word `Parser`.)

`Or` branches are evaluated by attempting to take each branch in sequence, entering the first branch which consumes some input. So when the first branch of the `Or` consumes the `<`, the parser commits to the first branch. Since the `<` is not followed by a `>` the parser then goes on to fail.

You have two options. One is to apply `Try`, to make the parser backtrack when it fails upon encountering the EOF:

```csharp
Try(Char('<').Then(Char('>')))
    .Or(...)
```

You can think of `Try` as dropping a bookmark in the input stream to which the parser can backtrack upon failure, somewhat like how `try`/`catch` in C# puts a bookmark in the call stack. Now, when the parser fails, it won't consume any input (because it backtracked), so the remaining branches of `Or` can be tried.

The other option is to combine the two branches of `Or` which begin with `<`, using `Optional` to distinguish inputs which continue with `>`.

```csharp
Char('<').Then(Char('>').Optional()).Select(mc => mc.HasValue ? 1 : 2)
        .Or(Char('>').ThenReturn(3))
        .Or(Char('=').ThenReturn(4));
```
