### ISSUE TITLE
How do I keep both sides of a match?

### ISSUE THREAD

**Issue by atrauzzi** [benjamin-hodgson/Pidgin#138]
I have:

```
Char('U').Then(Digit.Repeat(9)).Before(Char('_'))
```

The problem is that `Then` discards the `'U'` character instead of keeping it.  So if I have: `"U123456789"`, I end up getting `"123456789"`, whereas I'd like to get the string with `'U'` prefix.

It's almost like I want `Char('U').And(Digit.Repeat(9)).Before(Char('_'))`?

**Comment by RobRamSystems** [comment]
I think query syntax is the clearest (but watch out for performance!):

```
from c in Char('U')
from number in Digit.Repeat(9)
select $"{c}{number}"
```

In general, use `Map` if you need to combine the results of multiple sequential parsers in some way. The syntax above is basically a prettier way of using `Bind` which also allows you to do things like have a parser depend on the result of a previous parser, e.g.

```
from c in Char('U').Or(Char('S'))
from sign in c switch {
    'U' => Return(1),
    'S' => Char('-').Optional().Select(x => x.HasValue ? -1 : 1)
from number in Digit.Repeat(9)
select sign * int.Parse(number)
```

where it would only allow an optional minus sign if it started with 'S' instead of 'U'.

**Comment by benjamin-hodgson** [comment]
Thanks for fielding this @RobRamSystems!

**Comment by znakeeye** [comment]
Nice. But an answer using regular `LINQ` would be great to have too. Ideas?

**Comment by benjamin-hodgson** [comment]
[`Map`](https://www.benjamin.pizza/Pidgin/v3.2.3/Pidgin.Parser.html#Pidgin_Parser_Map__4_System_Func___1___2___3__Pidgin_Parser___0___1__Pidgin_Parser___0___2__), as @RobRamSystems suggested
