### ISSUE TITLE
Docs website is down

### ISSUE THREAD

**Issue by pdevito3** [benjamin-hodgson/Pidgin#145]
FYI in case you don't know, your docs site is down

**Comment by benjamin-hodgson** [comment]
Thanks for letting me know. I just changed registrars this week so it's possible that something got busted. Could be as simple as a stale DNS cache. It seems to be working for me tho (eg https://www.benjamin.pizza/Pidgin/v3.2.1/Pidgin), would you mind double-checking on your end?

**Comment by pdevito3** [comment]
weird. i can't get to it on my wifi, but works on my phone with cellular. internet is working otherwise on wifi though. just happening for the docs site.

wonder if xfinity doesn't like the DNS for some reason? 

assuming this is a google casualty? they're really improving the internet one day at a time 🙄

**Comment by benjamin-hodgson** [comment]
Yep, google domains 😣. It's a bummer as I was happy with it, but the domain was up for renewal next week anyway so I just took the opportunity and switched.

I've gotta assume it's just a DNS caching issue, since you can reach it ok with a different ISP. Give it a few days and hopefully it'll resolve itself. I'll try to remember to check in with you to see if it's sorted next week.

In the meantime I kicked off a build which should produce the doc site as an artifact: https://github.com/benjamin-hodgson/Pidgin/actions/runs/5340870451. You should be able to unzip `Pidgin.Docs.zip` and browse it locally. Hope this helps.

Note to self: include the docs site in the GitHub releases going forward

**Comment by pdevito3** [comment]
all good. i found it on wayback machine and am checking out one of your NDC talks on it to try and glean some info! 

i'll try and remember to check the next few days and update here too!

**Comment by pdevito3** [comment]
FYI, I'm on a random IDP (spectrum) at a hotel on the other side of the country and I'm still not able to access the docs 😕

**Comment by benjamin-hodgson** [comment]
What does `dig benjamin.pizza` show on your affected box?

**Comment by benjamin-hodgson** [comment]
Looks like this was a DNSSEC issue - the domain transfer brought the dnssec record with it even though it was no longer valid. I believe I've fixed the issue, let me know whether it's working for you now!

**Comment by pdevito3** [comment]
Works!

**Comment by benjamin-hodgson** [comment]
Sweet. Thanks!
