### ISSUE TITLE
Can you write an example for a Luau parser?

### ISSUE THREAD

**Issue by Shadowblitz16** [benjamin-hodgson/Pidgin#148]
Can you write an example for a Luau parser?

The reason why I pick luau is that..
- it's based on lua which is lightweight
- it has a type system
- it has generics
- it has unions
- it has intersections

**Comment by Shadowblitz16** [comment]
https://github.com/benjamin-hodgson/Pidgin/issues/149

**Comment by benjamin-hodgson** [comment]
I am not familiar with Luau. I certainly don't have time to write an example for every language out there, especially since production languages tend to be complex and have lots of syntactic surface area.

If you feel there's something specific missing from what's already out there (eg there's something you don't quite understand and want a more careful explanation) I can try to address that but I won't be adding this example myself. I'd accept a contribution.
