### ISSUE TITLE
Add ParseError as a context field to ParseException

### ISSUE THREAD

**Issue by thomaskejser** [benjamin-hodgson/Pidgin#155]
When constructing `ParseException`, it would be very useful to include the context from the ParseError:

```
private static T GetValueOrThrow<TToken, T>(Result<TToken, T> result)
        => result.Success ? result.Value : throw new ParseException(result.Error!.RenderErrorMessage(). <add result.Error here>);
```

This will allow code catching the `ParseException` to query the exception in a structured way about what went wrong

**Comment by benjamin-hodgson** [comment]
Fixed in c2a2b2e163091a34ed1bfeaf15fe789d1816a862. I had to add a subclass of `ParseException` with a `TToken` parameter in order to type the `ParseError` field correctly. So you can catch the more specific subclass and have access to the `Error`, or you can continue to catch the non-parameterised `ParseException` as before.

```csharp
try
{
    parser.ParseOrThrow("");
}
catch (ParseException<char> e)
{
    DoSomething(e.Error);
}
```
