### ISSUE TITLE
How to parse escaped string?

### ISSUE THREAD

**Issue by ejsmith** [benjamin-hodgson/Pidgin#2]
I'm trying to parse a quoted string with an escaped quote in it. I've tried a few variations of this with no success:

        private static readonly Parser<char, string> QuotedString =
            (String("\\\"").Or(Token(c => c != '"').ManyString())).Many().Select(System.String.Concat).Between(Quote);

Any ideas?

**Comment by benjamin-hodgson** [comment]
The problem is in this part, which I'll reformat for clarity:

```csharp
 String("\\\"")
     .Or(
         Token(c => c != '"').ManyString()
     )
```

This says:
1. Attempt to parse the literal string `\"`
2. If that fails without consuming any input, greedily parse as many non-`"` characters as you can.

Your program doesn't describe any way for the state machine to go from the second part of the `Or` to the first part, so you'll never catch an escaped `"` anywhere except right at the start of the string literal.

Here's how I'd write it instead:

```csharp
private static readonly Parser<char, char> EscapeCharacter =
    OneOf('"', 'n', 'r', 't', '\\')  // etc - list all the characters which are valid after a backslash
        .Labelled("escape character");

private static readonly Parser<char, string> QuotedString =
    Char('\\').Then(EscapedCharacter)
        .Or(Token(c => c != '"'))
        .ManyString()
        .Between(Quote)
        .Labelled("string literal");
```

This says:

1. Attempt to parse a `\` character
  a. If you do, then parse and return the second character in the escape sequence
  b. If that failed, parse any character other than `"`
2. Repeat greedily.

Note that this parser will fail if you encounter an unknown escape sequence. That's in line with how most programming languages do it, though.

Hope this helps!

**Comment by ejsmith** [comment]
Thank you! That seems to work good.

I am really liking the library, nice work!

**Comment by benjamin-hodgson** [comment]
😎
