### ISSUE TITLE
Streaming input?

### ISSUE THREAD

**Issue by hansmbakker** [benjamin-hodgson/Pidgin#26]
(Sorry if I misunderstand the goal of this library)

The parsers I found in the examples are all string-based. I'm wondering whether it is possible to create functionality using this library that takes a `Stream` as an input and that outputs parsed items through `event`s when new data is received through the input stream.

The use case for this is that I want to connect the incoming data `Stream` from a `SerialPort` object to my parser functionality, and I want it to emit parsed pieces of information to my GUI via `event`s.

**Comment by benjamin-hodgson** [comment]
There are a couple of different questions here. Regarding _streaming parsing_ - the idea that a parser should not buffer more input than it needs to - this is supported. You can write a parser that consumes `byte`s (ie `Parser<byte, MyParserOutput>`) and call [the `Stream` overload of `Parse`](https://github.com/benjamin-hodgson/Pidgin/blob/master/Pidgin/ParserExtensions.cs#L78). You can do the same with a `TextReader`, just replace `byte` with `char` in the previous sentence.

Your second question about `event`s is called _event-driven_ parsing, and is orthogonal to streaming parsing. (Streaming parsers may or may not be event-driven; event-driven parsers may or may not be streaming, although they usually are.) Event-driven parsing is a rather different paradigm than combinator parsing and not really supported in Pidgin at the moment, although I have thought about it. Doing it properly would likely require a pretty big redesign - there'd need to be some way to thread a user-supplied context object through the parsing process, which means adding a type parameter (ie `Parser<TToken, T>` becomes `Parser<TToken, TContext, T>`). Wouldn't make for a very nice API because C# doesn't feature type aliases.

You can hack around it though because C# an imperative language: you can lean on the specifics of _when_ the various lambdas are called during the parsing process. In an expression like `parser.Select(f)`, `f` is called when `parser` succeeds and returns a value. So  you can do something like this:

```csharp
interface ISerialPortEventListener
{
    void OnFoo(Foo foo);
    void OnBar(Bar bar);
}
Parser<Foo> FooParser;
Parser<Bar> BarParser;
void Parse(Stream input, ISerialPortEventListener listener)
{
    FooParser.Select(foo => { listener.OnFoo(foo); return Unit.Value; })
        .Or(
            BarParser.Select(bar => { listener.OnBar(bar); return Unit.Value; })
        )
        .Parse(stream);
}
```

In general this would require you to build a separate `Parser` object for each listener, which is potentially costly because it allocates heap memory. (Hence the need for a custom `TContext` type param to do this properly.)

Hope this answers your question?
