### ISSUE TITLE
Parsing code that defines new operators?

### ISSUE THREAD

**Issue by andrzejolszak** [benjamin-hodgson/Pidgin#33]
Hi Benjamin, how would one go about parsing a piece of code that defines new operators?
A motivating example is e.g. Prolog where one can:
```
:- op(200, xfy, =>>).
40 =>> 20.
```
I can see that ExpressionParser.Build takes an collection of operators, would it work to update the contents of the collection as the parsing progresses and we encounter new operator definitions?

**Comment by benjamin-hodgson** [comment]
You _could_ build a table of operators dynamically: Parse an `op` line and use `Then` to get hold of the resulting operator entry, use it to build a new `ExpressionParser` and continue from there. [Here's an example](http://dev.stephendiehl.com/fun/008_extended_parser.html#extensible-operators) of doing that using Parsec. It's a bit of a hack in Parsec, and it'd be even more of a hack in Pidgin because it doesn't support a user-defined state variable.

In my experience it tends to be easier to handle context-sensitive grammars like this at the same time as other context-sensitive checks like scope checking, ie, **after parsing**. Parse all operators (even unknown ones) in a uniform way, then fix up your expressions as an explicit tree traversal once you know the operators' associativity and precedence.

**Comment by andrzejolszak** [comment]
Great, thanks! :-)
