### ISSUE TITLE
[Question] Is there an easy way to get a breakdown of parsing performance?

### ISSUE THREAD

**Issue by davidaramant** [benjamin-hodgson/Pidgin#34]
What I mean is - get a breakdown of how many times each parser was called, how long each individual parser took, the total time spent for each parser, etc.  I tried profiling a parsing run with JetBrains dotTrace but it's, uh, not very helpful since it's just a massive chain of parser calls.

Is there a clever way to at least log how many times each parser is called by injecting a side effect somewhere?  I can fill in the other numbers from that.

**Comment by benjamin-hodgson** [comment]
@deanward81 actually asked me for something similar a couple of weeks ago. I like the idea, but I'm not sure it's something that I can easily provide as a library feature. The granularity at which you'd want profiling information - typically a lexeme, I think - doesn't match up with the granularity at which the library sees your code. That is to say, an identifier,

```csharp
var identifier = Letter.Then(LetterOrNumber.ManyString(), (h, t) => h + t);
```

is actually made of 4 or 5 different `Parser` objects talking to each other. In other words I don't think I can do a better job in the library than visual studio's built in profiler. If you want any sort of semantic profiling it would have to be written at the level of your language's semantics, that is, in your code.

Something you could do is write a custom higher-order `Parser` which measures its argument's running time. Something like this:

```csharp
static class ParserHelpers<TToken>
{
    public static Parser<TToken, T> Time<T>(
        Parser<TToken, T> p,
        [CallerMemberName] string label = null
    ) => StartStopwatch.Then(p, (sw, x) => {
        // the callback is invoked after p returns a result
        sw.Stop();
        RecordTimings(sw.Elapsed, label);
        return x;
    });

    private static Parser<TToken, Stopwatch> StartStopwatch
        = Return<Func<Stopwatch>>(Stopwatch.StartNew)
            .Then(f => f());
    private static void RecordTimings(TimeSpan ts, string label) { /* ... */ }
}
```

Then you can use it as

```csharp
var identifier = Time(
    Letter.Then(LetterOrNumber.ManyString(), (h, t) => h + t),
    "identifier"
);
```

The timings won't be 100% perfect, because they'll include the overhead of the `Then` call in `Time` (and possibly the overhead of recording the results), but it might be good enough for diagnosing an issue.

What do you think?

**Comment by davidaramant** [comment]
Thanks, I think I can adapt that to what I want.  Can I get the number of backtracks with this method?  Record parsing attempts where you start the stopwatch and completions where you stop it, or am I thinking about it wrong?

If I can get that info I can combine it with timing info from microbenchmarks using BenchmarkDotNet to get a good sense of which parsers might be problematic or worth optimizing.

**Comment by benjamin-hodgson** [comment]
You can actually detect failures directly, using [`RecoverWith`](https://www.benjamin.pizza/Pidgin/v2.1.0/api/Pidgin.Parser-2.html#Pidgin_Parser_2_RecoverWith_Func_Pidgin_ParseError__0__Pidgin_Parser__0__1___).

```csharp
p.RecoverWith(err => { RecordFailure(err); return Fail<T>(); })
```

Comes with overhead though (it has to compute the error) so you’ll wanna make sure you’re measuring the right thing!

**Comment by davidaramant** [comment]
I didn't want to leave this issue stranded, so here's what I ended up doing:

* I theorized that backtracking was one of the primary performance culprits in my parser (this was all for a hobby project; if I was doing this for money I would probably have done more due diligence in micro benchmarking).  The format I'm dealing with has both integers and floating point numbers.  I used to try the float parser first and fall back to the integer parser, meaning it would parse the integer portion multiple times.  My stress-test file is 2.7 million lines so this adds up...
* After some finagling I got a somewhat ugly "number" parser working that spit out an `object` (ugh) that was either an `int` or a `double`.  This one only parsed the integer portion of the number once.  And it worked! This reduced the parsing time by 1/3.
* I finally caved and figured that what I _really_ needed was a custom lexer, which I was dreading writing.  Pidgin did an admirable job shouldering both lexing and parsing duties but it was just too much overhead.  The lexer didn't end up being that tedious since the format is very simple.  Writing a recursive descent parser was a bridge too far for me though, and I used Pidgin to parse the token stream into my AST.   I'm happy with the results and I don't think an RDP would be appreciably faster.

Overall my parsing times for the monster file improved from 11.3 to 8 to 3 seconds.  Custom lexer + Pidgin parser was the fastest of the five different parser implementations I implemented and the code is pretty small and tidy.  I ended up doing a presentation about my parsing adventures at work and at a meetup and Pidgin was the once I ended up recommending to people 🙂 (and telling people to stay far away from parser generators, ugh).

**Comment by benjamin-hodgson** [comment]
Thanks for the update! It's a pleasant surprise to me that your custom token type performed well, since I haven't put a whole lot of effort into optimising that code path (beyond "it should work because generics") 😄 .

I'm always keen to understand how people are using my libraries in practice, so I'd be interested to see what your custom lexer looks like (I assume it's a streaming lexer?), and I'd also be interested in having a look at the slides from your talk, if that's something you'd be willing to share?

**Comment by davidaramant** [comment]
Yeah sure. [The slides](https://docs.google.com/presentation/d/165PXgg4YOUflM_AvslVtpRSi24mX4OH1ddP999vfQ1c) don’t have any speaker notes so some of the context is missing. It ended up primarily being an intro to how to use monadic parsers and a breakdown of the typical components of bigger parsers. 

[The example code](https://github.com/davidaramant/csharp-parsing-examples) that backs the talk is probably more interesting for you. Since I last posted here I also made a custom parser which ended up being the fastest approach. However, UDMF (the format I was parsing) is very simple and is also pretty set in stone at the syntax level, so a custom parser isn’t that bad. If the format were more complex or changed more often I think a custom parser would be objectively harder to maintain. I’m planning on giving lighting talk at work as an addendum to the bigger parsing talk with this caveat. 

I didn’t check what the error messages looked like for the custom lexer + pidgin combo but I suspect that might be a sore spot (does Pidgin count the tokens or something if it’s not working on text input?).
