### ISSUE TITLE
InvalidOperationException when calling Many 

### ISSUE THREAD

**Issue by stefnotch** [benjamin-hodgson/Pidgin#38]
I tried to use `Many()`, however it threw an exception.
```
System.InvalidOperationException: 'Many() used with a parser which consumed no input'
```

**Reproduction Code:**
` var x = Try(WhitespaceString.Many()).Parse("    ");`

**More details:**
`var x = Try(WhitespaceString).Parse("    ");` works just fine. 
However, if I want to skip whitespaces or comments, I have to write something along the lines of `var x = Try(WhitespaceString.Or(CommentString)).Parse("    ");`. This won't quite do the trick yet, since it can't handle a string that has whitespace *and* comments. To solve that, I tried using `.Many()` to apply "the current parser zero or more times". `var x = Try(WhitespaceString.Or(CommentString).Many()).Parse("    ");`
But that results in an exception.

**Comment by benjamin-hodgson** [comment]
`WhitespaceString` already does `Many` - it consumes zero-or-more whitespace characters, which is why it fails when passed to `Many`. You probably want to consume one-or-more whitespace characters or a comment many times. (That sentence to be parsed as `((one-or-more whitespace characters) or a comment) many times`.)

That would be:

```
Whitespace.SkipAtLeastOnce().Or(SkipComment).Many();
```
