### ISSUE TITLE
New token streams

### ISSUE THREAD

**Issue by beho** [benjamin-hodgson/Pidgin#47]
Hi,

we would like to use Pidgin for parsing data received using [`ReadOnlySequence<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.readonlysequence-1?view=netcore-3.0). I'm experimenting with implementation in [beho/Pidgin/read-only-sequence](https://github.com/beho/Pidgin/tree/read-only-sequence).

I was forced to fork this repository because `ITokenStream` as the essential extension point for creating new token streams is marked internal. I would very much like to be able to use your build of Pidgin (and be able to update by simply updating nuget package) than having to merge new commits into a fork.

So the question is – is there any plan to publish `ITokenStream` for external consumers or is it something you would be willing to consider? Or from opposite perspective, is there any reason preventing you from making this interface public?

Thanks for great work!

beho

**Comment by benjamin-hodgson** [comment]
The reason I kept `ITokenStream` internal originally is because I anticipated that I'd want to change its design. It has in fact changed a lot since [the initial implementation](https://github.com/benjamin-hodgson/Pidgin/tree/5fd43ae58c581d8b9ffbf4dffdf8807b1ace9f7f/Pidgin/ParseStates). Publishing it would mean it can't ever be changed again so I'd need to be certain I was done with the design.

However, I do have my sights set on publishing `ITokenStream` for v3.0.  It feels a lot more solid now than in the past. There are a couple of things which I'd consider tweaking to make it production-ready:

1. Perhaps `ReadInto` should take a `Span` as its argument, rather than an array with `start`/`length`?
2. Should `ChunkSizeHint` have a default implementation? It would mean changing from an interface to an abstract class.

Anyway, `ReadOnlySequence` seems like something we can probably support directly in the library, since `System.Buffers` is an existing dependency. I'd be happy to accept a pull request.

**Comment by benjamin-hodgson** [comment]
I looked into this a bit, and it turns out the reason I used an array and not a `Span` was for the `TextReader`/`Stream` implementations of `ITokenStream`. Those APIs on Framework/Standard don't have `Read(Span)` methods. You can of course copy the data into an intermediate buffer (inside the `TokenStream`); I haven't investigated how expensive this would be

**Comment by TehPers** [comment]
I would also love this, if only to update the input's `ChunkHintSize`. Currently, it's not possible to parse at the same time as reading input from `Console.In`, a TCP stream, etc. Creating a custom `ITokenStream` would probably fix that.

**Comment by benjamin-hodgson** [comment]
@TehPers Could you elaborate on what you found difficult about parsing from streams?

**Comment by TehPers** [comment]
@benjamin-hodgson I was trying to parse from `Console.In` for debugging, but it seems like I might have been doing it incorrectly, whoops!

**Comment by beho** [comment]
I realised that `ReadOnlySequence` per se does not solve my problem because it represents a fininite sequence. What is really required for my use-case is parsing of non-allocating stream of tokens, so probably [PipeReader](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipereader?view=dotnet-plat-ext-3.0). It basically allows repeated reads with result provided in `ReadOnlySequence`. So I will continue with prototyping and create pull request when I have something workable.

Data in pipe need to be marked as consumed when parsing completes successfully. How do I get number of consumed tokens? There is `_consumedCount` field in `ParserState` but it does not surface in `Result`.

**Comment by beho** [comment]
> However, I do have my sights set on publishing `ITokenStream` for v3.0. It feels a lot more solid now than in the past. There are a couple of things which I'd consider tweaking to make it production-ready:
> 
>     1. Perhaps `ReadInto` should take a `Span` as its argument, rather than an array with `start`/`length`?
>
There is `Stream.Read(Span<Byte>)` in .NET Standard 2.1 Preview ([docs](https://docs.microsoft.com/en-us/dotnet/api/system.readonlyspan-1?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.ReadOnlySpan%601);k(DevLang-csharp)%26rd%3Dtrue&view=netstandard-2.1)). So there would need to be two methods, each targeting different platforms.

>     2. Should `ChunkSizeHint` have a default implementation? It would mean changing from an interface to an abstract class.

I see two values currently – 16 for collections/enumerators and 4096 for streaming sources (`Stream`, `TextReader`). It seems to be source-specific value and as such needs to be given some thought so I wouldn't provide default value.

**Comment by beho** [comment]
@benjamin-hodgson did you consider async token streams (eg. applicable to `StreamTokenStream`)?

**Comment by benjamin-hodgson** [comment]
`async` is a whoooole other kettle of fish.

**Comment by benjamin-hodgson** [comment]
Fixed in https://github.com/benjamin-hodgson/Pidgin/commit/e9c9b79912406bb792c1b98b6ff2a9e45670c417 (on the v3 branch)
