### ISSUE TITLE
Issue with parsing for one character and whitespace

### ISSUE THREAD

**Issue by powerdude** [benjamin-hodgson/Pidgin#52]
Hi,

I have the following test case:

```
        [TestMethod]
        public void Bug()
        {
            var mins= OneOf(Tok("minutes"), Tok("mins"), Tok("min")).Trace(x => $"mins={x}");
            var meters=OneOf(Tok("meters"), CIString("m").Before(WhitespaceString)).Trace(x => $"meters={x}");

            meters.ParseOrThrow("min Run");
        }

```

I would expect the `meters` parser to throw because it should be looking for "m " and failing.  Am i doing something wrong here?

**Comment by benjamin-hodgson** [comment]
Thanks for getting in touch!

`WhitespaceString` consumes any sequence of whitespace characters, **including an empty sequence**. So your `meters` parser operates like this on the input:

1. Attempt to read a `meters` token, which fails upon encountering the `i`.
2. Backtrack and attempt to read an `m` character. This succeeds and the parser commits to the branch
3. Consume any number of whitespace characters. Since the current character is `i`, there are 0 whitespace characters, so `WhitespaceString` returns an empty string.

You probably want to read **at least one** whitespace character after each of your tokens, which means tweaking your `Tok` combinator to use `Whitespace.SkipAtLeastOnce()` instead of `SkipWhitespaces`.

Without knowing more about the grammar you’re trying to parse I can’t say whether that’s something you want to apply to every token or only some of them (in which case you might want a separate `Keyword` combinator). And if it’s legal to have a non-whitespace symbol character after your keywords then you might need to use some combination of `Lookahead` and `Not` in your `Keyword` combinator instead of just consuming at least one whitespace character. Something like

```csharp
static Parser Keyword(Parser p)
    => Tok(p.Before(Lookahead(Not(ValidIdentifierCharacter))));
```

Hope this helps!

**Comment by powerdude** [comment]
It does help, thanks!
