### ISSUE TITLE
Any plans to make use of new Span support?

### ISSUE THREAD

**Issue by ejsmith** [benjamin-hodgson/Pidgin#8]
https://msdn.microsoft.com/en-us/magazine/mt814808.aspx

**Comment by benjamin-hodgson** [comment]
I've thought about this previously. Briefly: I'm excited about `Span`, but I'm not yet sure how it'd fit into a parser combinator library in a general way.

The problem is that there's no distinction between parsers which return data directly from the input stream (like `Char` and `String` and parsers which return some calculated value. For example, you couldn't implement `Parser<Span<T>> ManySpan(this Parser<T> parser)` in general without copying, because there's no way to know that the `T`s that `parser` returns are in fact taken from some underlying storage.

I think the way to go would probably be to make `ManySpan` return a view into the input stream where possible and a view into an intermediate array otherwise. This carries a risk of unpredictable performance but could pay off if you know what you're doing.

I do have a half-formed plan to improve the performance of parsers like `String` to reduce the number of virtual calls by adding some methods to `IParseState`. I think this idea would fit into that framework quite nicely.

**Comment by ejsmith** [comment]
Yeah that makes sense. Would it just be used under the covers for the source content and traversing it without allocation for slices? I think you may be doing something similar already but Span is supposed to have some support at the CLR level to make it faster that a hand rolled string segment solution.

**Comment by benjamin-hodgson** [comment]
https://github.com/benjamin-hodgson/Pidgin/commit/5fcfb06a25093c7b75826c68a8681a12a0dfb97a

**Comment by benjamin-hodgson** [comment]
Shipped in v2.0.0

**Comment by benjamin-hodgson** [comment]
oh and also https://github.com/benjamin-hodgson/Pidgin/commit/f4651bb67f2cb8330a0befbdb83b8d83f05efeba
