### ISSUE TITLE
Any.AtleastOnceUntil Fails Unexpectadly.

### ISSUE THREAD

**Issue by pnquest** [benjamin-hodgson/Pidgin#91]
Given the parser

```C#
Any.AtLeastOnceUntil(String("bags").Or(String("bag")));
```
I would expect all of the following inputs to parse successfully, however any second word that starts with b prior to bags fails. Additionally any use of bag instead of bags fails.

|Input|Result|
|-----|------|
|great green bag|fails|
|great green bags|passes|
|great orange bag|fails|
|great orange bags|passes|
|great blue bag|fails|
|great blue bags|fails|
|blue bag|fails|
|blue bags|passes|
|black bags|passes|
|black bag|fails|

The seems like a bug, but maybe I am misunderstanding how this is supposed to work?

**Comment by benjamin-hodgson** [comment]
`Or` commits to the first branch which consumes input. The `bags` parser encounters and consumes the `b` of `bag` but later fails when it doesn't see the `s`. `Or` never attempts the second parser because the first one consumed input.

The simplest fix is to enable [backtracking](https://www.benjamin.pizza/Pidgin/v2.5.0/api/Pidgin.Parser.html#Pidgin_Parser_Try__2_Pidgin_Parser___0___1__) on your `bags` parser:

```csharp
Try(String("bags")).Or(String("bag")))
```

Then `bags` will backtrack to the initial `b` when it fails, and `Or` will be able to try the `bag` parser.

See [my website](https://www.benjamin.pizza/posts/2019-12-08-parsing-prolog-with-pidgin.html#handling-tokens-and-whitespace) for a more detailed explanation.

**Comment by pnquest** [comment]
@benjamin-hodgson thanks for the quick response!

Just tried this out and I actually had to use `Try(String("bags")).Or(Try(String("bag")))` for some reason, but it otherwise worked out great. Thanks!

**Comment by benjamin-hodgson** [comment]
Ah yeah, that's cos you're using it inside an `Until` (which basically uses `Or` under the hood).
