### ISSUE TITLE
'@' in String parser?

### ISSUE THREAD

**Issue by tstockwell** [benjamin-hodgson/Pidgin#99]
Hi Benjamin,

First, thanks for Pidgin and Sawmill!

I am using them to build a Razor UI generator and I've run into a little problem.
The example below fails with the message `unexpected u  expected "@attribute" at line 1, col 2 `

```
                    var source = "@using";
                    var parser = OneOf(String("@attribute"), String("@using"));
                    var parseResults = parser.Parse(source);

```

But this example works....
```
                    var source = "using";
                    var parser = OneOf(String("attribute"), String("using"));
                    var parseResults = parser.Parse(source);

```

I'm completely stumped, why are the extra '@' characters harshing my buzz? :-)

Thanks in advance,
-ted

**Comment by lstefano71** [comment]
Pidgin's parsers  don't backtrack by default. In your first example, you one want one of two parsers. But by the time the first parser matches the first "@", the second one will never be tried because Pidgin has settled on the first one. Alas, the first one is bound to fail, because "a" from "attribute" is not equal to "u". You want to either match the "@" and then go OneOf, or permit the backtracking by using "Try". Check the section "Choosing from alternatives" in Pidgin's Readme for an example. The relevant section starts with "If one of Or or OneOf's component parsers fails after consuming input, the whole parser will fail.".

**Comment by benjamin-hodgson** [comment]
I endorse @lstefano71's answer! The reason your second example works is because the parser can tell the two keywords apart by looking only at their first letter. The `attribute` parser never consumes any input, so `OneOf` doesn't commit to it.

**Comment by benjamin-hodgson** [comment]
I have a more worked out example on my personal website: https://www.benjamin.pizza/posts/2019-12-08-parsing-prolog-with-pidgin.html#handling-tokens-and-whitespace

**Comment by tstockwell** [comment]
DOH! 
Thanks to all!
